name: LagScore
version: ${project.version}
main: net.dohaw.play.lagscore.LagScore
api-version: 1.13
depend:
  - CoreAPI

commands:
  lagscore:
    aliases:
      - ls
      - lags
      - lscore

permissions:
  lagscore.use:
    default: op
