name: LagScore
version: ${project.version}
main: relocated.net.dohaw.lagscore.LagScore
api-version: 1.13

commands:
  lagscore:
    aliases:
      - ls
      - lags
      - lscore

permissions:
  lagscore.use:
    default: op
